import Head from 'next/head'
import Layout from '@/components/ui/utils/Layout'
import { useRouter } from 'next/router'
import GameButton from '@/components/ui/utils/GameButton'
import { LINKS, PLAY_ROUTES } from '@/libs/constants'
import { toast } from 'react-toastify'
import { useAuth } from '@/contexts/AuthContext'
import ModalWrapper from '@/components/modals/ModalWrapper'
import CreateProfileForm from '@/components/modals/CreateProfileForm'
import { useState } from 'react'

export default function Home() {

  const router = useRouter()

  const [open, setOpen] = useState(false)

  const { currentUser, userProfile } = useAuth()

  const quickGame = () => {
    router.push(PLAY_ROUTES.QUICKGAME)
  }

  const PVE = () => {
    if (pleaseConnect()) return
    router.push(PLAY_ROUTES.PLAY_PVE)
  }

  const PVP = () => {
    if (pleaseConnect()) return
    router.push(LINKS.CREATE_MATCH)
  }

  const pleaseConnect = () => {
    if (currentUser?.loggedIn) {
      if (!userProfile) {
        setOpen(true)
        return true
      }
      return false
    }
    toast.error("Please connect your wallet to proceed")
    return true
  }

  const handleClose = () => {
    setOpen(false)
  }

  return (
    <>
      <Head>
        <title>Tik tak on flow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <div data-aos="fade-up" className='flex flex-grow flex-col justify-center items-center text-white w-full'>

          <GameButton onClick={quickGame} color='blue'>Quick Game</GameButton>

          <GameButton onClick={PVE} color={'red'}>Play With Flow</GameButton>

          {/* <GameButton onClick={PVP} color='yellow'>Play With Friends</GameButton> */}

        </div>

      </Layout>

      <ModalWrapper title={"Create Account"} open={open} handleClose={handleClose}>
        <CreateProfileForm handleClose={handleClose} />
      </ModalWrapper>

    </>
  )
}
 