import Head from 'next/head'
import Layout from '@/components/ui/utils/Layout'
import Container from '@/components/ui/utils/Container'
import { useRouter } from 'next/router'
import GameButton from '@/components/ui/utils/GameButton'
import { LINKS } from '@/libs/constants'

export default function Home() {

  const router = useRouter()

  const play = () => {
    router.push("/play")
  }

  return (
    <>
      <Head>
        <title>Tik tak on flow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <div data-aos="fade-up" className='flex flex-grow flex-col justify-center items-center text-white w-full'>


          <GameButton onClick={play} color='blue'>Play With Bot</GameButton>

          <GameButton onClick={() => router.push(LINKS.ACHIEVEMENTS)} color='blue'>Achiements</GameButton>

          <GameButton onClick={() => router.push(LINKS.LEADERBOARD)} color='blue'>LeaderBoard</GameButton>

          <GameButton onClick={() => router.push(LINKS.MATCH_HISTORY)} color='blue'>Match History</GameButton>
          

        </div>

      </Layout>

    </>
  )
}
