import Head from 'next/head'
import { useEffect, useState } from 'react'
import Layout from '@/components/ui/utils/Layout'
import PlayOptions from '@/components/game/PlayOptions'
import Fight from '@/components/game/Fight'
import { PLAYER_MOVE } from '@/libs/constants'
import GameStatus from '@/components/game/GameStatus'
import useGamePVEPlay from '@/hooks/useGamePVEPlay'
import { useAuth } from '@/contexts/AuthContext'
import ModalWrapper from '@/components/modals/ModalWrapper'
import GameEnded from '@/components/modals/GameEnded'
import { toast } from 'react-toastify'

export default function MatchHistory() {

    const { currentUser, userProfile } = useAuth()

    console.log(userProfile)


    return (
        <>
            <Head>
                <title>Play</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
 
            </Layout>

        </>
    )
}
 