import Head from 'next/head'
import Layout from '@/components/ui/utils/Layout'
import Container from '@/components/ui/utils/Container'
import PlayOptions from '@/components/ui/game/PlayOptions'
import { useState } from 'react'

export default function Home() {

    const [option, setOption] = useState(0)

    console.log(option)

    return (
        <>
            <Head>
                <title>Play</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>

                <div className='flex items-center justify-center w-full'>

                    <PlayOptions setOption={setOption} />

                </div>

            </Layout>

        </>
    )
}
